#!/bin/bash

NAME="redis"
DISPLAY_NAME="Redis"
TYPE="component"
VARIANTS=${VARIANTS:-"default,alpine"}
VERSIONS=${VERSIONS:-"3,4"}

DOCKER_PUSH=${DOCKER_PUSH:-"false"}

source $(readlink -zf $(dirname "${BASH_SOURCE[0]}"))/../common/hack/run
