#!/bin/bash

NAME="redis"
DISPLAY_NAME="Redis"
REPO="redis-component"
TYPE="component"
VARIANT="alpine"
VERSIONS="3.2"

DOCKER_PUSH=${DOCKER_PUSH:-"false"}

source $(readlink -zf $(dirname "${BASH_SOURCE[0]}"))/../common/hack/run
